select flyerid,count(flyerid ) from MasterAdviewData..AdActCWM									group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masteradviewdata..hispanic									group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from MasterAdviewData..Production								group by flyerid having count(flyerid ) > 1 union 
--select flyerid,count(flyerid ) from MasterAVData..MasterAVChildWebMain							group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..EPAAABBDMChildWebMain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..EPAMBBDAAAChildWebMain				group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..EPAMBBDAAAFlyerReports				group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..EPAMFBEChildWebMain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..EPAMFChildWebMain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..EPASMChildWebMain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..EPCANChildWebMain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..EPPRDChildWebMain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..EPUSWebChildWebMain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from MasterClientCoverage..FRAdCWM								group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from MasterClientCoverage..FSIEntryChildWebMain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from MasterClientCoverage..jaAdamsChildWebMain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from MasterClientCoverage..jaALCChildWebMain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..JaAllChildWebMain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..JAASMChildWebMain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..JABAChildWebMain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..JABEVChildWebMain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..JACANChildwebmain						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..JADRINKSChildWebMain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from MasterClientCoverage..JaHSPeChildWebmain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from MasterClientCoverage..JaHSPSChildWebmain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..JAInetCANChildwebmain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..JAMASSChildWebMain					group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..jaSPANChildWebMain					group by flyerid having count(flyerid ) > 1 union 
--select flyerid,count(flyerid ) from masterclientcoverage..SP11FlyerReports						group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..TblCanada								group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..TblDigital							group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..Tblemail								group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..TblFsiDetail							group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..TblNoNOnline							group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..TblOnline								group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..TblPuertoRico							group by flyerid having count(flyerid ) > 1 union 
select flyerid,count(flyerid ) from masterclientcoverage..TblPuertoRicoDetail					group by flyerid having count(flyerid ) > 1  
--select flyerid,count(flyerid ) from masterclientcoverage..USCAFlyerReports						group by flyerid having count(flyerid ) > 1  
