



Select Distinct Advertiser, Market, Media, Count(Distinct FlyerId) #Ads
from MasterAdviewData..AdviewMain 
Where Year(Addate)=2018 and
(  (Advertiser='Academy' and Market='Austin, TX' and Media='Insert-Digital' )
OR (Advertiser='Apple Group' and Market='Oklahoma City, OK' and Media='Insert-Paper' )
OR (Advertiser='Assc Whlsl Grocers - III' and Market='Springfield, MO' and Media='Insert-Digital' )
OR (Advertiser='Bass Pro' and Market='Birmingham, AL' and Media='Insert-Digital' )
OR (Advertiser='Bass Pro' and Market='New Orleans, LA' and Media='Insert-Digital' )
OR (Advertiser='Bass Pro' and Market='Oklahoma City, OK' and Media='Insert-Digital' )
OR (Advertiser='Bass Pro' and Market='San Antonio, TX' and Media='Insert-Digital' )
OR (Advertiser='Best Buy' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Best Buy' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Best Buy' and Market='National' and Media='In-store' )
OR (Advertiser='Big Lots' and Market='Columbus, OH' and Media='Insert-Digital' )
OR (Advertiser='BJs Wholesale Club' and Market='Buffalo, NY' and Media='Insert-Digital' )
OR (Advertiser='BJs Wholesale Club' and Market='Buffalo, NY' and Media='Insert-Paper' )
OR (Advertiser='Buehlers Fresh Foods' and Market='Akron, OH' and Media='Insert-Digital' )
OR (Advertiser='Cabelas' and Market='Austin, TX' and Media='Insert-Digital' )
OR (Advertiser='CVS' and Market='Albany, NY' and Media='FSI' )
OR (Advertiser='CVS' and Market='Albany, NY' and Media='Insert-Paper' )
OR (Advertiser='CVS' and Market='Albany, NY' and Media='ROP' )
OR (Advertiser='CVS' and Market='Greensboro, NC' and Media='Insert-Paper' )
OR (Advertiser='CVS' and Market='Minneapolis/St.Paul, MN' and Media='FSI' )
OR (Advertiser='CVS' and Market='Minneapolis/St.Paul, MN' and Media='Insert-Paper' )
OR (Advertiser='CVS' and Market='Pittsburgh, PA' and Media='FSI' )
OR (Advertiser='CVS' and Market='Pittsburgh, PA' and Media='Insert-Paper' )
OR (Advertiser='CVS' and Market='Springfield, MA' and Media='Insert-Paper' )
OR (Advertiser='Dans Supermarket' and Market='Bismarck, ND' and Media='Insert-Paper' )
OR (Advertiser='Dicks' and Market='Austin, TX' and Media='Insert-Digital' )
OR (Advertiser='Dicks' and Market='Birmingham, AL' and Media='Insert-Digital' )
OR (Advertiser='Dicks' and Market='Charlotte, NC' and Media='Insert-Digital' )
OR (Advertiser='Dicks' and Market='San Antonio, TX' and Media='Insert-Digital' )
OR (Advertiser='Dollar General' and Market='Atlanta, GA' and Media='Insert-Digital' )
OR (Advertiser='Dollar General' and Market='Atlanta, GA' and Media='Insert-Paper' )
OR (Advertiser='Dollar General' and Market='Baltimore, MD' and Media='FSI' )
OR (Advertiser='Dollar General' and Market='Baltimore, MD' and Media='Insert-Digital' )
OR (Advertiser='Dollar General' and Market='Denver, CO' and Media='Insert-Digital' )
OR (Advertiser='Dollar General' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Dollar General' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Dollar General Market' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Dollar General Market' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Elrods' and Market='Dallas, TX' and Media='Insert-Paper' )
OR (Advertiser='Family Dollar' and Market='Albany, NY' and Media='FSI' )
OR (Advertiser='Family Dollar' and Market='Albany, NY' and Media='Insert-Digital' )
OR (Advertiser='Family Dollar' and Market='Albany, NY' and Media='Insert-Paper' )
OR (Advertiser='Family Dollar' and Market='Atlanta, GA' and Media='FSI' )
OR (Advertiser='Family Dollar' and Market='Atlanta, GA' and Media='Insert-Digital' )
OR (Advertiser='Family Dollar' and Market='Atlanta, GA' and Media='Insert-Paper' )
OR (Advertiser='Family Dollar' and Market='Denver, CO' and Media='Insert-Digital' )
OR (Advertiser='Family Dollar' and Market='Denver, CO' and Media='Insert-Paper' )
OR (Advertiser='Field & Stream' and Market='Charleston, SC' and Media='Insert-Digital' )
OR (Advertiser='Field & Stream' and Market='Greensboro, NC' and Media='Insert-Digital' )
OR (Advertiser='Foods Co' and Market='Sacramento, CA' and Media='Insert-Paper' )
OR (Advertiser='Foodtown' and Market='Newark, NJ' and Media='Insert-Paper' )
OR (Advertiser='HEB' and Market='Corpus Christi, TX' and Media='Insert-Digital' )
OR (Advertiser='HEB' and Market='Corpus Christi, TX' and Media='Insert-Paper' )
OR (Advertiser='HEB' and Market='Laredo, TX' and Media='Insert-Digital' )
OR (Advertiser='HEB' and Market='Laredo, TX' and Media='Insert-Paper' )
OR (Advertiser='HEB (z75)' and Market='Houston, TX' and Media='Insert-Digital' )
OR (Advertiser='HEB (z75)' and Market='Houston, TX' and Media='Insert-Paper' )
OR (Advertiser='HEB Plus' and Market='Austin, TX' and Media='Insert-Digital' )
OR (Advertiser='HEB Plus' and Market='Austin, TX' and Media='Insert-Paper' )
OR (Advertiser='HEB Plus' and Market='San Antonio, TX' and Media='Insert-Digital' )
OR (Advertiser='HEB Plus' and Market='San Antonio, TX' and Media='Insert-Paper' )
OR (Advertiser='Home Depot' and Market='Albany, NY' and Media='Insert-Digital' )
OR (Advertiser='Home Depot' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='IGA' and Market='Charleston, SC' and Media='Insert-Digital' )
OR (Advertiser='IGA' and Market='Charleston, SC' and Media='ROP' )
OR (Advertiser='IGA' and Market='Great Falls, MT' and Media='Insert-Paper' )
OR (Advertiser='IGA' and Market='Great Falls, MT' and Media='Insert-Pick Up In-Store' )
OR (Advertiser='Jo-Ann Fabrics And Crafts' and Market='Atlanta, GA' and Media='Insert-Digital' )
OR (Advertiser='Jo-Ann Fabrics And Crafts' and Market='Baltimore, MD' and Media='Insert-Digital' )
OR (Advertiser='Jo-Ann Fabrics And Crafts' and Market='Cincinnati, OH' and Media='Insert-Digital' )
OR (Advertiser='Jo-Ann Fabrics And Crafts' and Market='Los Angeles, CA' and Media='Insert-Digital' )
OR (Advertiser='Jo-Ann Fabrics And Crafts' and Market='Miami, FL' and Media='Insert-Digital' )
OR (Advertiser='Jo-Ann Fabrics And Crafts' and Market='Philadelphia, PA' and Media='Insert-Digital' )
OR (Advertiser='Jo-Ann Fabrics And Crafts' and Market='Seattle, WA' and Media='Insert-Digital' )
OR (Advertiser='Kmart' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Kmart' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Kroger' and Market='Fort Worth, TX' and Media='Insert-Digital' )
OR (Advertiser='Kroger' and Market='Fort Worth, TX' and Media='Insert-Paper' )
OR (Advertiser='Kroger Marketplace' and Market='Cincinnati, OH' and Media='Insert-Digital' )
OR (Advertiser='Kroger Marketplace' and Market='Cincinnati, OH' and Media='Insert-Paper' )
OR (Advertiser='Lowes' and Market='Albany, NY' and Media='Insert-Digital' )
OR (Advertiser='Lowes' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Lowes Mercado' and Market='Denver, CO' and Media='Insert-Digital' )
OR (Advertiser='Lowes Mercado' and Market='Denver, CO' and Media='Insert-Paper' )
OR (Advertiser='Meijer' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Meijer' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Menards' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Michaels' and Market='Boston, MA' and Media='Insert-Paper' )
OR (Advertiser='Office Depot' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Office Depot' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Office Depot' and Market='National' and Media='ROP' )
OR (Advertiser='Pet Supermarket' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Pet Supplies Plus' and Market='Chicago, IL' and Media='Insert-Digital' )
OR (Advertiser='Pet Supplies Plus' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Baltimore, MD' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Baltimore, MD' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Boston, MA' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Boston, MA' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Cincinnati, OH' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Cincinnati, OH' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Houston, TX' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Houston, TX' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Kansas City, MO' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Kansas City, MO' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Los Angeles, CA' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Los Angeles, CA' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Minneapolis/St.Paul, MN' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Minneapolis/St.Paul, MN' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Newark, NJ' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Newark, NJ' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Philadelphia, PA' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Philadelphia, PA' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Phoenix, AZ' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Pittsburgh, PA' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Pittsburgh, PA' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Sacramento, CA' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Sacramento, CA' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='San Diego, CA' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='San Diego, CA' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='St. Louis, MO' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='St. Louis, MO' and Media='Insert-Paper' )
OR (Advertiser='Petco' and Market='Wichita, KS' and Media='Insert-Digital' )
OR (Advertiser='Petco' and Market='Wichita, KS' and Media='Insert-Paper' )
OR (Advertiser='Petsmart' and Market='Albany, NY' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Albany, NY' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Baltimore, MD' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Baltimore, MD' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Boston, MA' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Boston, MA' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Cincinnati, OH' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Cincinnati, OH' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Cleveland, OH' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Cleveland, OH' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Columbus, OH' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Columbus, OH' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Detroit, MI' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Detroit, MI' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Houston, TX' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Houston, TX' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Indianapolis, IN' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Indianapolis, IN' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Kansas City, MO' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Kansas City, MO' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Los Angeles, CA' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Los Angeles, CA' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Minneapolis/St.Paul, MN' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Minneapolis/St.Paul, MN' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Petsmart' and Market='National' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Newark, NJ' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Newark, NJ' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Oklahoma City, OK' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Oklahoma City, OK' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Philadelphia, PA' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Philadelphia, PA' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Phoenix, AZ' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Phoenix, AZ' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Reno, NV' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Reno, NV' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='Sacramento, CA' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='Sacramento, CA' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='San Diego, CA' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='San Diego, CA' and Media='In-store' )
OR (Advertiser='Petsmart' and Market='St. Louis, MO' and Media='Insert-Digital' )
OR (Advertiser='Petsmart' and Market='St. Louis, MO' and Media='In-store' )
OR (Advertiser='Publix' and Market='Columbia, SC' and Media='Insert-Paper' )
OR (Advertiser='Restaurant Depot' and Market='Atlanta, GA' and Media='Insert-Digital' )
OR (Advertiser='Restaurant Depot' and Market='Atlanta, GA' and Media='Insert-Pick Up In-Store' )
OR (Advertiser='Restaurant Depot' and Market='Oklahoma City, OK' and Media='Insert-Digital' )
OR (Advertiser='Rite-Aid' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Rite-Aid' and Market='Pittsburgh, PA' and Media='Insert-Paper' )
OR (Advertiser='Rite-Aid' and Market='Springfield, MA' and Media='Insert-Paper' )
OR (Advertiser='Rouses' and Market='Baton Rouge, LA' and Media='Insert-Digital' )
OR (Advertiser='Rouses' and Market='Baton Rouge, LA' and Media='ROP' )
OR (Advertiser='Shopko' and Market='Boise, ID' and Media='Insert-Digital' )
OR (Advertiser='Shopko' and Market='Boise, ID' and Media='Insert-Paper' )
OR (Advertiser='Shopko' and Market='Green Bay, WI' and Media='Insert-Digital' )
OR (Advertiser='Shopko' and Market='Green Bay, WI' and Media='Insert-Paper' )
OR (Advertiser='Shopko' and Market='Madison, WI' and Media='Insert-Digital' )
OR (Advertiser='Shopko' and Market='Madison, WI' and Media='Insert-Paper' )
OR (Advertiser='Shopko' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Shopko' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Shopko' and Market='Salt Lake City, UT' and Media='Insert-Digital' )
OR (Advertiser='Shopko' and Market='Salt Lake City, UT' and Media='Insert-Paper' )
OR (Advertiser='Shopko' and Market='Salt Lake City, UT' and Media='ROP' )
OR (Advertiser='Staples' and Market='Cleveland, OH' and Media='Insert-Digital' )
OR (Advertiser='Staples' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Staples' and Market='National' and Media='ROP' )
OR (Advertiser='The Fresh Market' and Market='Cincinnati, OH' and Media='Insert-Paper' )
OR (Advertiser='The Fresh Market' and Market='Raleigh/Durham, NC' and Media='Insert-Paper' )
OR (Advertiser='Total Wine & More' and Market='San Francisco, CA' and Media='Insert-Digital' )
OR (Advertiser='Total Wine & More' and Market='San Francisco, CA' and Media='ROP' )
OR (Advertiser='Tractor Supply Co' and Market='Austin, TX' and Media='Insert-Digital' )
OR (Advertiser='Tractor Supply Co' and Market='El Paso, TX' and Media='Insert-Digital' )
OR (Advertiser='Tractor Supply Co' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Tractor Supply Co' and Market='San Antonio, TX' and Media='Insert-Digital' )
OR (Advertiser='Ulta' and Market='National' and Media='Insert-Digital' )
OR (Advertiser='Walgreens' and Market='Charleston, SC' and Media='Insert-Paper' )
OR (Advertiser='Walgreens' and Market='Charleston, SC' and Media='In-store' )
OR (Advertiser='Walgreens' and Market='Charleston, SC' and Media='ROP' )
OR (Advertiser='Walgreens' and Market='Fresno, CA' and Media='Insert-Paper' )
OR (Advertiser='Walgreens' and Market='Fresno, CA' and Media='In-store' )
OR (Advertiser='Walgreens' and Market='National' and Media='Insert-Paper' )
OR (Advertiser='Walgreens' and Market='National' and Media='In-store' )
OR (Advertiser='Walgreens' and Market='National' and Media='ROP' )
OR (Advertiser='Walgreens' and Market='Reno, NV' and Media='Insert-Paper' )
OR (Advertiser='Walgreens' and Market='Reno, NV' and Media='In-store' )
OR (Advertiser='Walgreens' and Market='San Jose, CA' and Media='Insert-Paper' )
OR (Advertiser='Walgreens' and Market='San Jose, CA' and Media='In-store' )
OR (Advertiser='Walgreens' and Market='Springfield, MA' and Media='Insert-Paper' )
OR (Advertiser='Walgreens' and Market='Springfield, MA' and Media='In-store' )
OR (Advertiser='Walmart' and Market='Little Rock, AR' and Media='Insert-Digital' )
OR (Advertiser='Walmart' and Market='Little Rock, AR' and Media='Insert-Paper' )
OR (Advertiser='Walmart' and Market='Springfield, MO' and Media='Insert-Digital' )
OR (Advertiser='Walmart' and Market='Springfield, MO' and Media='Insert-Paper' )
OR (Advertiser='Walmart' and Market='Wichita, KS' and Media='Insert-Digital' )
OR (Advertiser='Walmart' and Market='Wichita, KS' and Media='Insert-Paper' )
OR (Advertiser='Wegmans' and Market='Newark, NJ' and Media='Insert-Paper' )
OR (Advertiser='Weis' and Market='Newark, NJ' and Media='Insert-Paper' )
OR (Advertiser='Whole Foods' and Market='Albany, NY' and Media='Insert-Digital' )
OR (Advertiser='Whole Foods' and Market='Detroit, MI' and Media='Insert-Digital' )
OR (Advertiser='Whole Foods' and Market='Philadelphia, PA' and Media='Insert-Digital' )
OR (Advertiser='Whole Foods' and Market='Philadelphia, PA' and Media='ROP' )
OR (Advertiser='Whole Foods' and Market='St. Louis, MO' and Media='Insert-Digital' )) 
Group by Advertiser, Market, Media
Order by 1,2,3