SELECT * INTO TEMPDB..AC FROM TEMPDB..UNITDISCPRICEMASTER WHERE UNITDISCOUNTPRICE IS NOT NULL  AND PAGEDETAILID IN (
SELECT A.SourcePageDetailId  FROM ACFVCDETAILMAP A JOIN TEMPDB..UNITDISCPRICEMASTER B ON 
A.DestPageDetailId =B.PAGEDETAILID AND  B.PAGEDETAILID LIKE '%EC')



SELECT * FROM TEMPDB..AC 

SELECT * FROM TEMPDB..UNITDISCPRICEMASTER WHERE PAGEDETAILID LIKE '%EC'

ALTER TABLE TEMPDB..UNITDISCPRICEMASTER ADD MASTERpdtid VARCHAR(20)

--UPDATE  A  SET MASTERPDTID = M.SOURCEPAGEDETAILID FROM TEMPDB..UNITDISCPRICEMASTER A JOIN ACFVCDETAILMAP M ON A.PageDetailId =M.DESTPAGEDETAILID

SELECT * FROM TEMPDB..UNITDISCPRICEMASTER
WHERE PAGEDETAILID IN ('011105083EC','0003324E467')




SELECT * into tempdb..ec FROM TEMPDB..UNITDISCPRICEMASTER WHERE PAGEDETAILID LIKE '%EC' and unitdiscountprice is not null 

select * from tempdb..ec 



