SELECT DISTINCT YEAR(ADDATE),COUNT(1)   FROM MASTERADVIEWDATA..ADVIEWMAIN A JOIN TempJAPageDetailTable B ON A.FLYERID=B.FLYERID  WHERE ProdImageCreated =0 AND PageDetailID LIKE '%DC' 
GROUP BY YEAR(ADDATE)
ORDER BY 1 

2015	246
2016	173360
2017	33239
2018	23433


SELECT * FROM PIProcessingTableTempMCAP WHERE PageDetailID LIKE '%DC'

SELECT * FROM MasterMappingTables..DurPDTMapCons WHERE CONSPageDetailId IN (
SELECT PAGEDETAILID  FROM PIProcessingTableTempMCAP WHERE PageDetailID LIKE '%DC')


--tempja3232018
SELECT count(1)   FROM MASTERADVIEWDATA..ADVIEWMAIN A JOIN TempJAPageDetailTable B ON A.FLYERID=B.FLYERID  WHERE ProdImageCreated =0 AND PageDetailID LIKE '%DC' 
and  YEAR(ADDATE) <> '2018'
ORDER BY 1 


--update b set ProdImageCreated =1   FROM MASTERADVIEWDATA..ADVIEWMAIN A JOIN TempJAPageDetailTable B ON A.FLYERID=B.FLYERID  WHERE ProdImageCreated =0 AND PageDetailID LIKE '%DC' and  YEAR(ADDATE) <> '2018'
